GET http://localhost:3001/api/notes/
// ### below are separators for 'REST client'
###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "Not Postman",
    "important": "true"
}